title: The Crying Limpkin
author: JEM
email: 
description: > # this means to ignore newlines until "baseurl:"
  Adventures in Fl
  
# social links
twitter_username:  # DO NOT include the @ character, or else the build will fail!
github_username:   # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
